## Alcohol and students
Data source: https://www.kaggle.com/datasets/uciml/student-alcohol-consumption?resource=download

In [45]:
import pandas as pd

mat_df = pd.read_csv('student-mat.csv')
por_df = pd.read_csv('student-por.csv')

## Remove unrelevant attributes and rename grade attribute

In [46]:
por_df = por_df.drop(columns=['school', 'famsize', 'famsup', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'schoolsup', 'paid', 'nursery', 'internet', 'G1', 'G2'])
por_df = por_df.rename(columns = {'G3':'grade'})

mat_df = mat_df.drop(columns=['school', 'famsize', 'famsup', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'schoolsup', 'paid', 'nursery', 'internet', 'G1', 'G2'])
mat_df = mat_df.rename(columns = {'G3':'grade'})

In [48]:
print(por_df)
print(mat_df)

    sex  age address Pstatus  studytime  failures activities higher romantic  \
0     F   18       U       A          2         0         no    yes       no
1     F   17       U       T          2         0         no    yes       no
2     F   15       U       T          2         0         no    yes       no
3     F   15       U       T          3         0        yes    yes      yes
4     F   16       U       T          2         0         no    yes       no
..   ..  ...     ...     ...        ...       ...        ...    ...      ...
644   F   19       R       T          3         1        yes    yes       no
645   F   18       U       T          2         0         no    yes       no
646   F   18       U       T          2         0        yes    yes       no
647   M   17       U       T          1         0         no    yes       no
648   M   18       R       T          1         0         no    yes       no

     famrel  freetime  goout  Dalc  Walc  health  absences  grade
0         4         3      4     1     1       3         4     11
1         5         3      3     1     1       3         2     11
2         4         3      2     2     3       3         6     12
3         3         2      2     1     1       5         0     14
4         4         3      2     1     2       5         0     13
..      ...       ...    ...   ...   ...     ...       ...    ...
644       5         4      2     1     2       5         4     10
645       4         3      4     1     1       1         4     16
646       1         1      1     1     1       5         6      9
647       2         4      5     3     4       2         6     10
648       4         4      1     3     4       5         4     11

[649 rows x 17 columns]
    sex  age address Pstatus  studytime  failures activities higher romantic  \
0     F   18       U       A          2         0         no    yes       no
1     F   17       U       T          2         0         no    yes       no
2     F   15       U       T          2         3         no    yes       no
3     F   15       U       T          3         0        yes    yes      yes
4     F   16       U       T          2         0         no    yes       no
..   ..  ...     ...     ...        ...       ...        ...    ...      ...
390   M   20       U       A          2         2         no    yes       no
391   M   17       U       T          1         0         no    yes       no
392   M   21       R       T          1         3         no    yes       no
393   M   18       R       T          1         0         no    yes       no
394   M   19       U       T          1         0         no    yes       no

     famrel  freetime  goout  Dalc  Walc  health  absences  grade
0         4         3      4     1     1       3         6      6
1         5         3      3     1     1       3         4      6
2         4         3      2     2     3       3        10     10
3         3         2      2     1     1       5         2     15
4         4         3      2     1     2       5         4     10
..      ...       ...    ...   ...   ...     ...       ...    ...
390       5         5      4     4     5       4        11      9
391       2         4      5     3     4       2         3     16
392       5         5      3     3     3       3         3      7
393       4         4      1     3     4       5         0     10
394       3         2      3     3     3       5         5      9

[395 rows x 17 columns]

In [57]:
mat_df.corr()

,age,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,grade
age,1.000000,-0.004140,0.243665,0.053940,0.016434,0.126964,0.131125,0.117276,-0.062187,0.175230,-0.161579
studytime,-0.004140,1.000000,-0.173563,0.039731,-0.143198,-0.063904,-0.196019,-0.253785,-0.075616,-0.062700,0.097820
failures,0.243665,-0.173563,1.000000,-0.044337,0.091987,0.124561,0.136047,0.141962,0.065827,0.063726,-0.360415
famrel,0.053940,0.039731,-0.044337,1.000000,0.150701,0.064568,-0.077594,-0.113397,0.094056,-0.044354,0.051363
freetime,0.016434,-0.143198,0.091987,0.150701,1.000000,0.285019,0.209001,0.147822,0.075733,-0.058078,0.011307
goout,0.126964,-0.063904,0.124561,0.064568,0.285019,1.000000,0.266994,0.420386,-0.009577,0.044302,-0.132791
Dalc,0.131125,-0.196019,0.136047,-0.077594,0.209001,0.266994,1.000000,0.647544,0.077180,0.111908,-0.054660
Walc,0.117276,-0.253785,0.141962,-0.113397,0.147822,0.420386,0.647544,1.000000,0.092476,0.136291,-0.051939
health,-0.062187,-0.075616,0.065827,0.094056,0.075733,-0.009577,0.077180,0.092476,1.000000,-0.029937,-0.061335
absences,0.175230,-0.062700,0.063726,-0.044354,-0.058078,0.044302,0.111908,0.136291,-0.029937,1.000000,0.034247
grade,-0.161579,0.097820,-0.360415,0.051363,0.011307,-0.132791,-0.054660,-0.051939,-0.061335,0.034247,1.000000

In [58]:
por_df.corr()

,age,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,grade
age,1.000000,-0.008415,0.319968,-0.020559,-0.004910,0.112805,0.134768,0.086357,-0.008750,0.149998,-0.106505
studytime,-0.008415,1.000000,-0.147441,-0.004127,-0.068829,-0.075442,-0.137585,-0.214925,-0.056433,-0.118389,0.249789
failures,0.319968,-0.147441,1.000000,-0.062645,0.108995,0.045078,0.105949,0.082266,0.035588,0.122779,-0.393316
famrel,-0.020559,-0.004127,-0.062645,1.000000,0.129216,0.089707,-0.075767,-0.093511,0.109559,-0.089534,0.063361
freetime,-0.004910,-0.068829,0.108995,0.129216,1.000000,0.346352,0.109904,0.120244,0.084526,-0.018716,-0.122705
goout,0.112805,-0.075442,0.045078,0.089707,0.346352,1.000000,0.245126,0.388680,-0.015741,0.085374,-0.087641
Dalc,0.134768,-0.137585,0.105949,-0.075767,0.109904,0.245126,1.000000,0.616561,0.059067,0.172952,-0.204719
Walc,0.086357,-0.214925,0.082266,-0.093511,0.120244,0.388680,0.616561,1.000000,0.114988,0.156373,-0.176619
health,-0.008750,-0.056433,0.035588,0.109559,0.084526,-0.015741,0.059067,0.114988,1.000000,-0.030235,-0.098851
absences,0.149998,-0.118389,0.122779,-0.089534,-0.018716,0.085374,0.172952,0.156373,-0.030235,1.000000,-0.091379
grade,-0.106505,0.249789,-0.393316,0.063361,-0.122705,-0.087641,-0.204719,-0.176619,-0.098851,-0.091379,1.000000